services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/Staging:cached
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    command: sleep infinity
